### ISSUE TITLE
bosh-dns wait script

### ISSUE THREAD

**Issue by cppforlife** [jfmyers9/etcd-release#1]
possibly replace 

```
/var/vcap/packages/bosh-dns/bin/bosh-dns-wait --checkDomain upcheck.bosh-dns. --timeout 5m
```

with

```
/var/vcap/jobs/bosh-dns/bin/wait
```

in pre-start.

**Comment by jfmyers9** [comment]
@cppforlife ~~Can't because of BPM. This is yet another example of wanting to access something from `/var/vcap/jobs`. Open to other suggestions.~~

I see. `pre-start`. Will look at it. Does BOSH DNS become available before the BOSH DNS job is started?

**Comment by jfmyers9** [comment]
@cppforlife I would be interested in seeing better documentation around this is the [BOSH DNS documentation](https://bosh.io/docs/dns.html). It was unclear that this script exists or could be properly run inside the `pre-start`.
